backend:
  name: github
  repo: JANRIASD/mensaje-esperanza
  branch: main

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "mensajes"
    label: "Mensajes"
    folder: "mensajes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}

